
development:
  adapter: mysql2
  encoding: utf8
  database: bursatil_develop
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: bursatil_prod
  pool: 5
  username: root
  password: root
  socket: /tmp/mysql.sock
